'use strict';
(()=>{
const C=CUP,S=Scoring,$=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number(x).toLocaleString('zh-CN',{maximumFractionDigits:2});
const KEY='shangwai-cup-3-v1';let local={schemaVersion:1,records:{},policy:{...C.defaultPolicy}},official={schemaVersion:1,records:{},policy:{...C.defaultPolicy}},publicState='loading',selectedDay='2026-09-19',selectedTeam='duck',selectedPlayer={fun:'lan',competitive:'mumu'},boardSource='official',detailsId=null,storageMessage='修改自动保存于当前浏览器',toastTimer;
try{const saved=localStorage.getItem(KEY);if(saved)local=S.validate(JSON.parse(saved));}catch(e){storageMessage='本地存档无法读取。请先导出或检查浏览器存储设置。';}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4200);}
function persist(){local.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(local));storageMessage='已保存到此浏览器 · '+new Date().toLocaleTimeString('zh-CN');}catch(e){storageMessage='浏览器未能保存，请导出 JSON 备份。';}const x=$('.status-save');if(x)x.textContent=storageMessage;}
function player(id){return C.players.find(x=>x.id===id);}
function pAvatar(p){return `<span class="avatar" role="img" aria-label="${esc(p.name)}头像" style="background-position:-134px -${222+p.row*54.5}px"></span>`;}
function pIdentity(p){return `<div class="player">${pAvatar(p)}<div><strong>${esc(p.name)} ${p.pressure?'<span class="pill purple">抗压位</span>':''}</strong><small>${p.difficulty} · ${esc(p.squad)}分队</small></div></div>`;}
function route(){const [raw,sub]=location.hash.slice(1).split('/');return {track:raw==='fun'?'fun':'competitive',page:raw==='fun'||raw==='competitive'?(sub||'schedule'):'home'};}
function home(){return `<section class="home-hero"><h1 class="sr-only">上外杯 #3 · 沉沦者的黑流树海</h1><a href="assets/poster.png" target="_blank" rel="noopener" aria-label="查看上外杯第三届完整海报"><img class="poster" src="assets/poster.png" alt="上外杯 #3 多语种主题海报：沉沦者的黑流树海，2026年9月19日至28日，娱乐赛道与竞技赛道" width="1672" height="941"></a><div class="hero-caption"><span><strong>赛事预告</strong> &nbsp; / &nbsp; 集成战略 · 沉沦者的黑流树海</span><span>09.19 — 09.28 &nbsp; BEIJING TIME</span></div></section>
<div class="container"><div class="entry-grid"><a class="entry" href="#fun"><span class="index" aria-hidden="true">01</span><span class="kicker">Recreational</span><h2>娱乐赛道</h2><p>自由选择难度，探索阵营与招募的更多可能。</p><div class="entry-foot"><span>4 位选手 · 按日查看赛程</span><b>进入娱乐赛道 ↗</b></div></a><a class="entry competitive" href="#competitive"><span class="index" aria-hidden="true">02</span><span class="kicker">Competitive</span><h2>竞技赛道</h2><p>N15 团队对决，协同抓位与全追猎挑战。</p><div class="entry-foot"><span>2 支队伍 · 6 位选手</span><b>进入竞技赛道 ↗</b></div></a></div>
<div class="stats"><div class="stat"><strong>10</strong><span>参赛选手</span></div><div class="stat"><strong>02</strong><span>竞技队伍</span></div><div class="stat"><strong>09.19</strong><span>首场比赛</span></div><div class="stat"><strong>09.28</strong><span>末场比赛</span></div></div>
<div class="section-top"><h2>首日赛程</h2><a class="meta" href="#fun/schedule">查看娱乐赛程 ↗</a></div>${C.players.filter(p=>p.date==='2026-09-19').map(p=>match(p)).join('')}
<div class="home-bottom"><span>竞技赛道包含团队赛，仅竞技选手参与组队。</span><a href="assets/schedule.png" target="_blank" rel="noopener">查看原始赛程图 ↗</a></div></div>`;}
function match(p){return `<article class="match"><div class="match-time">${p.time}<small>${p.date.slice(5).replace('-','.')}</small></div>${pIdentity(p)}<a class="btn secondary small" href="#${p.track}/calculator" data-player="${p.id}">打开计分台</a></article>`;}
function header(track,page){const fun=track==='fun';return `<div class="race-header"><div class="container"><a class="breadcrumb" href="#home">← 返回赛事首页</a><div class="race-heading"><div><div class="kicker">${fun?'01 / RECREATIONAL':'02 / COMPETITIVE'}</div><h1>${fun?'娱乐赛道':'竞技赛道'}</h1><p>${fun?'4 位选手 · 自选难度 · 独立个人计分':'2 支队伍 · 6 位选手 · N15 · D 类团队配置'}</p></div><span class="pill ${fun?'accent':'purple'}">${fun?'09.19 — 09.23':'09.20 — 09.28'}</span></div><nav class="tabbar" aria-label="赛道栏目">${[['schedule','赛程'],['rules','规则'],['scores','得分'],['calculator','计分台']].map(([id,name])=>`<a href="#${track}/${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${name}</a>`).join('')}</nav></div></div>`;}
function schedule(track){if(track==='fun'){
const selected=C.players.filter(p=>p.track==='fun'&&p.date===selectedDay);return `<div class="section-top"><h2>每日赛程</h2><span class="meta">拟定时间 · 北京时间 UTC+8</span></div><div class="date-strip" role="group" aria-label="选择比赛日期">${Array.from({length:10},(_,i)=>{const day='2026-09-'+(19+i),n=C.players.filter(p=>p.track==='fun'&&p.date===day).length;return `<button class="date ${day===selectedDay?'active':''} ${!n?'inactive':''}" data-day="${day}" aria-pressed="${day===selectedDay}"><small>9月 · ${['六','日','一','二','三','四','五'][(i)%7]}</small><strong>${19+i}</strong><small>${n?n+' 场比赛':'无娱乐赛'}</small></button>`;}).join('')}</div><div class="day-heading"><h2>${selectedDay.slice(5).replace('-',' / ')}</h2><span class="pill">${selected.length} 场</span></div>${selected.length?selected.map(match).join(''):'<div class="empty">当日未安排娱乐赛道比赛。请选择其他日期。</div>'}<div class="notice info">娱乐赛道独立计分，不参与团队成绩与竞技队内抓位池。</div><div class="sourcebar"><a class="btn secondary small" href="assets/schedule.png" target="_blank" rel="noopener">原始赛程图 ↗</a></div>`;}
const t=C.teams.find(t=>t.id===selectedTeam),teamScore=S.workbook(official.records,official.policy).teams.find(x=>x.id===t.id);return `<div class="section-top"><h2>团队赛程</h2><span class="meta">三人一队 · 抗压位独立抓位池</span></div><div class="team-tabs" role="group" aria-label="选择队伍">${C.teams.map(t=>`<button class="team-tab ${selectedTeam===t.id?'active':''}" data-team="${t.id}" aria-pressed="${selectedTeam===t.id}">${t.name}</button>`).join('')}</div><div class="team-summary"><div><h2>${t.name}</h2><p>3 名竞技选手 · 2 名常规位 + 1 名抗压位</p></div><div class="team-total"><small>团队已发布分数</small><strong>${teamScore.entered?fmt(teamScore.total):'—'}</strong><small>${teamScore.entered} / 3 已录入</small></div></div>${t.members.map(player).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(match).join('')}<div class="notice info">队内共用 200 存款；一次超取权利；最多两次额外重开。常规位共用 5、6 星抓位池，抗压位独立使用一个池子，额外倍率 +0.10。</div><div class="sourcebar"><a class="btn secondary small" href="assets/teams.png" target="_blank" rel="noopener">原始队伍图 ↗</a><a class="btn secondary small" href="assets/schedule.png" target="_blank" rel="noopener">原始赛程图 ↗</a></div>`;}
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const rule=(id,title,body)=>`<section class="rule-section" id="rule-${id}"><h3>${title}</h3>${body}</section>`;
function rules(track){const fun=track==='fun';const sections=[];
sections.push(['start','参赛与开局',`<p>在集成战略“沉沦者的黑流树海”中进行比赛。${fun?'娱乐赛道可以自行选择难度。':'竞技赛道统一 N15，参与 D 类三人团队赛。'}</p><ul><li>无襁褓开局，可自行选择特定的开局奖励。</li><li>开始时进度不得超过初始招募；随心所欲开局应停留在初始招募组合选择界面。</li><li>赛程采用提供截图中的拟定比赛时间，均按北京时间展示。</li></ul>`]);
sections.push(['formula','基础计分',fun?'<div class="formula">个人最终分 = 个人结算分 × 0.8 + 关卡规则分</div><p>本页将道中、结局、临招、特殊敌人、阵营和少人奖励归入加分项。</p>':`<div class="formula">个人最终分 =（个人结算分 − 7.5 × 零件数 + 结算加分 + 关卡规则分）× 总倍率 − 违规扣分<br>总倍率 = 分队系数 + 全追猎通关系数 + 机械师禁用系数 + 抗压位系数</div>${table(['分队 / 条件','系数'],[['多边贸易','0.85'],['文明开化 / 地面突破 / 高台突破','1.10'],['其余分队','1.00'],['全追猎状态通关','额外 +0.20'],['赛前声明禁用机械师','额外 +0.05'],['D 类抗压位','额外 +0.10']])}<p>文明开化分队通关且全程未遇实托邦（不含希望的沃土）：结算分 +300。</p>`]);
sections.push(['hunt','追猎与结局',`${table(['道中追猎关卡',fun?'加分（同名一次）':'无漏加分（队内一次）'],C.hunts.map(x=>[x[1],'+'+x[fun?2:3]]))}<p>${fun?'娱乐赛道的道中追猎奖励按个人同名关卡一次计算。':'全追猎状态：不交换探测先锋，且进入节点或通过关卡前每层均进行非“不期而遇”出现的追猎作战。小八界传至偏安一隅不破坏状态。'}</p>${table(['结局关卡','基础','无漏','额外条件'],fun?[['永无安宁','150','100','—'],['苦痛将息','200','100','—'],['混沌源阶理论','250','100','—'],['畸症','300','200','击杀症结之核 +200']]:[['痛苦将息','200','100','全追猎状态通关 +200'],['混沌源阶理论','250','100','—'],['畸症','100','100','击杀症结之核 +200；全追猎 +150，或追猎3 +75（两者互斥）']])}`]);
if(fun){sections.push(['special','娱乐特殊加分',`<ul><li>临时招募：每名六星 +40、五星 +15、四星 +5。</li><li>每击杀一个鸭 / 狗 / 熊 / 鼠，+20。</li><li>以下阵营至少 3 名干员可获得 +400：${C.factions.join('、')}。</li><li>Ave Mujica 五人齐全（丰川祥子、三角初华、若叶睦、八幡海铃、祐天寺若麦），对应奖励改为 +600。</li><li>S.E.E.S. 四人齐全（结城理、岳羽由加莉、埃癸斯、虎狼丸），对应奖励改为 +600。</li><li>完成任意结局，结算页面不超过 5 位干员：+(6 − X) × 120。临招计入 X，应急助力不计入。</li></ul><p>多个阵营是否叠加，原文没有明确说明；默认只取最高一项，可由裁判调整。</p>`]);}
else{
sections.push(['recruit','抓位与机械师',`<ul><li>职业队仅抓取 2 名六星外援：结算分 +300。职业队为突击战术、破坏战术、堡垒战术、远程战术分队。</li><li>非职业队每职业仅抓取 1 名六星，可赛前声明一个职业放宽为 2 名：满足条件结算分 +300。</li><li>机械师必须赛前声明选项：禁用 +400 且倍率 +0.05；仅局外收益 +100；仅局内收益 +200。三者互斥。</li><li>禁用机械师时，“后备精通 I”带来的开局一次应急助力仍可使用。</li><li>仅局外：不将机械师编入编队；仅局内：不使用容量 +2 与结构性原理。</li></ul>`]);
sections.push(['special','特殊关卡与藏品',`${table(['无漏关卡（队内同名一次）','层数与分数'],C.specials.map(s=>[s.name+(s.wonder?' · 误入奇境限定':''),Object.entries(s.levels).map(([k,v])=>k+'层 +'+v).join(' / ')]))}<ul><li>紧急同域共存：+70；黑流地脉 +70；全追猎状态 +50；非 6 层 +20；黑流地脉与全追猎同时满足，额外 +150。</li><li>在窥视箱进入痛苦将息（箱中猎影）：结算分 +70，无需在 6 层进入调和仪式。</li><li>同时持有沙盘 α 与 β 且通关：+150。</li><li>三供无削：同时持有所需三供藏品或源私钥，在调谐仪式选择“不必依靠外物”且通关，+300。完整措辞见原文。</li><li>遇到复得之轮 / 果腹不抓取，或不可抗力获得但全局不触发效果：结算分 +200。两件是否分别计分可切换口径。</li><li>零件箱全局遵守单板藤限制，额外板藤第一时间无条件丢弃（不得出售）：结算分 +200。</li></ul>`]);
sections.push(['team','D 类团队规则',`<p>本届采用 <strong>3 名竞技选手</strong> 的 D 类配置，娱乐选手不组队。文档中的 A / B / C 混合赛道方案为历史备选，不适用于当前名单。</p><ul><li>全队存款 200。“生命游戏—瘤胃”的存款 +5 不计入。用种子培育出襁褓，团队存款 +5。</li><li>全队一次超取权：可在一个商店内吸满 12 块，不计入全队存款。</li><li>全队最多 2 次、每人最多 1 次额外重开：在进入 II 层未移动前使用，可再次烧取指定开局；不重置取款与超取权。</li><li>两名非抗压位共用 5、6 星抓位池（全 5、6 星限 1），抗压位独立使用一个池子。</li><li>应急助力、临时招募不占队内池子。竞技不限时长，无速通、额外藏品、临招或隐藏分；明确列出的藏品规则分仍按竞技规则计算。</li><li>连麦最多 3 次，每次 3 分钟，可连续使用，使用前与工作人员沟通。</li><li>队内首次通关痛苦将息 +100，首次通关混沌源阶理论 +100。</li></ul><h3>抗压位的五项限制</h3><ol><li>前两位选手开局主力六星全程禁用。</li><li>全程最多抓取 2 名五星。</li><li>进入卡德霍之颅前获得“焚毁‘文明’”。</li><li>初始种子不可种植、不可在一层商店售出。</li><li>不可交换探测先锋。</li></ol><p>每违反一条 −1000；抗压位全追猎仍是可选项。扣分位置见下方计分口径。</p>`]);
}
sections.push(['policy','计分口径与复核',`<div class="notice">${C.policyNote}</div><p>队内唯一关卡按截图赛程先后，将分数分配给第一位勾选达成条件且已填写结算分的选手。同名特殊关卡跨层也只领取一次。实际发生顺序不同，应由裁判调整并填写原因。</p><p>特殊关卡与同域共存的重复通关未定义叠加次数，当前每名选手按同名一次录入。不同结局可同时计入；畸症的全追猎 +150 与追猎3 +75 自动互斥。</p><p>“满足抓位奖励”等复选项代表裁判已核实全部前提，系统不会从游戏录像自动判断。正式成绩只读取网站发布的数据，本地计分不会自动公开。</p>`]);
return `<div class="sourcebar"><a class="btn secondary small" href="rules/${track}.docx" download>下载${fun?'娱乐':'竞技'}规则原文</a>${!fun?'<a class="btn secondary small" href="rules/team.docx" download>下载团队规则原文</a>':''}<span class="meta">以当前赛道配置整理 · 保留原始文件供复核</span></div><div class="rule-layout"><aside class="rule-nav" aria-label="规则目录">${sections.map(([id,title])=>`<a href="#rule-${id}" data-rule="${id}">${title}</a>`).join('')}</aside><div>${sections.map(([id,title,body])=>rule(id,title,body)).join('')}<details class="rule-section"><summary>查看原始${fun?'娱乐':'竞技'}规则全文（含历史更新）</summary><div class="raw-rule">${esc(RULE_SOURCES[track])}</div></details>${!fun?`<details class="rule-section"><summary>查看团队规则全文（含历史 A / B / C 配置）</summary><div class="raw-rule">${esc(RULE_SOURCES.team)}</div></details>`:''}</div></div>`;}
function sources(){return `<div class="score-source"><label for="score-source">成绩来源</label><select id="score-source" class="source-select"><option value="official" ${boardSource==='official'?'selected':''}>已发布成绩</option><option value="local" ${boardSource==='local'?'selected':''}>本地试算（未发布）</option></select><span class="meta">${boardSource==='local'?'仅当前浏览器可见':publicState==='ready'?(official.updatedAt?'发布记录更新于 '+esc(new Date(official.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})):'尚未发布比赛成绩'):publicState==='error'?'成绩文件加载失败，请刷新重试。':'正在读取成绩…'}</span></div>`;}
function scoreDetails(p,r,score){return `<div class="audit"><strong>${p.name} · 计分明细</strong><div class="formula">${p.track==='fun'?`${fmt(score.raw)} × 0.8 + ${fmt(score.level)} − ${fmt(score.penalty)} + ${fmt(score.manual)}`:`(${fmt(score.raw)} + ${fmt(score.extra)} − ${fmt(score.parts)} + ${fmt(score.level)}) × ${score.multiplier} − ${fmt(score.penalty)} + ${fmt(score.manual+score.afterBonus)}`} = ${fmt(score.total)}</div>${score.lines.map(l=>`<div class="line">${esc(l.label)} <b>${l.value>=0?'+':''}${fmt(l.value)}</b></div>`).join('')}${score.warnings.map(w=>`<p class="notice">${esc(w)}</p>`).join('')}${r.adjustReason?`<p>调整说明：${esc(r.adjustReason)}</p>`:''}${r.notes?`<p>裁判备注：${esc(r.notes)}</p>`:''}</div>`;}
function scores(track){const source=boardSource==='local'?local:official,w=S.workbook(source.records,source.policy),ps=C.players.filter(p=>p.track===track).sort((a,b)=>Number(w.scores[b.id].entered)-Number(w.scores[a.id].entered)||w.scores[b.id].total-w.scores[a.id].total);return `${sources()}${boardSource==='local'?'<div class="notice">当前展示本地试算，不属于正式成绩。完整队内去重需要录入同队全部已完成场次。</div>':''}${track==='competitive'?`<div class="section-top"><h2>团队得分</h2><span class="meta">未完成全部场次时仅展示累计分，不确定最终名次</span></div><div class="table-scroll"><table class="board"><thead><tr><th>名次</th><th>队伍</th><th>已录入</th><th>个人分合计</th><th>团队奖励</th><th>总分</th></tr></thead><tbody>${w.teams.sort((a,b)=>b.total-a.total).map((t,i)=>`<tr><td>${w.teams.every(x=>x.entered===3)?(i&&t.total===w.teams[i-1].total?'并列':i+1):'—'}</td><td>${t.name}</td><td>${t.entered} / 3</td><td>${t.entered?fmt(t.total-t.firstBonus):'—'}</td><td>${t.entered?'+'+t.firstBonus:'—'}</td><td class="score">${t.entered?fmt(t.total):'待录入'}</td></tr>`).join('')}</tbody></table></div>`:''}<div class="section-top"><h2>个人得分</h2><span class="meta">${track==='fun'?'按最终得分排序':'团队成员明细'}</span></div><div class="table-scroll"><table class="board"><thead><tr><th>选手</th><th>${track==='fun'?'难度 / 分队':'所属队伍'}</th><th>结算分</th><th>最终分</th><th>明细</th></tr></thead><tbody>${ps.map(p=>{const s=w.scores[p.id];return `<tr><td>${pIdentity(p)}</td><td>${track==='fun'?p.difficulty+' / '+p.squad:C.teams.find(t=>t.id===p.team).name}</td><td>${s.entered?fmt(s.raw):'—'}</td><td class="score">${s.entered?fmt(s.total):'待录入'}</td><td>${s.entered?`<button class="btn secondary small" data-detail="${p.id}">展开明细</button>`:'—'}</td></tr>`;}).join('')}</tbody></table></div>${detailsId&&source.records[detailsId]&&player(detailsId).track===track?scoreDetails(player(detailsId),source.records[detailsId],w.scores[detailsId]):''}<p class="meta" style="margin-top:20px">暂无结果的场次显示“待录入”。赛程结束后，成绩仍以实际发布数据为准。</p>`;}
function numberField(r,key,title,{integer=false,hint='',max=10000000,min=0}={}){return `<div class="field"><label for="f-${key}">${title}</label><input id="f-${key}" name="${key}" type="number" inputmode="decimal" value="${esc(r[key]??'')}" min="${min}" max="${max}" step="${integer?1:'any'}" ${key==='base'?'placeholder="输入游戏结算分"':''}>${hint?`<small>${hint}</small>`:''}</div>`;}
function check(r,key,title,bonus='',hint='',parent=''){return `<label class="check"><input type="checkbox" name="${key}" ${r[key]?'checked':''} ${parent?`data-parent="${parent}" ${!r[parent]?'disabled':''}`:''}><span class="check-label">${title}${hint?`<small>${hint}</small>`:''}</span>${bonus?`<span class="bonus">${bonus}</span>`:''}</label>`;}
function selectField(r,key,title,options){return `<div class="field"><label for="f-${key}">${title}</label><select name="${key}" id="f-${key}">${options.map(([v,l])=>`<option value="${v}" ${String(r[key]??0)===String(v)?'selected':''}>${l}</option>`).join('')}</select></div>`;}
function calcSection(n,title,body){return `<section class="calc-section"><h3><span class="step">${n}</span>${title}</h3>${body}</section>`;}
function policyForm(){return `<details class="calc-section"><summary>裁判口径 · 四项待确认条款</summary><p class="meta">以下选项作用于整份计分文件，并随导出保存；当前仅影响本地试算。</p><div class="fields">${[['factions','娱乐阵营奖励',[['best','默认：只取最高一项'],['each','各达标阵营分别累加']]],['relics','复得之轮 / 果腹',[['combined','默认：两项合计最多 +200'],['each','每件分别 +200']]],['dPenalty','D 类违规扣分位置',[['after','默认：总倍率之后扣分'],['before','总倍率之前扣分']]],['firstClear','D 类首次结局奖励',[['team','默认：直接计入团队总分'],['before','计入首通者倍率前分数'],['after','计入首通者倍率后分数']]]].map(([k,title,opts])=>`<div class="field"><label for="policy-${k}">${title}</label><select id="policy-${k}" data-policy="${k}">${opts.map(([v,l])=>`<option value="${v}" ${local.policy[k]===v?'selected':''}>${l}</option>`).join('')}</select></div>`).join('')}</div></details>`;}
function calculator(track){const p=player(selectedPlayer[track]),r=local.records[p.id]||S.fresh(p),fun=track==='fun';let form='';
form+=calcSection('01','基础记录',`<div class="fields">${numberField(r,'base','游戏结算分')}${fun?'':numberField(r,'parts','零件数量',{integer:true,hint:'每个零件扣除 7.5 分'})}${fun?'':selectField(r,'squad','使用分队',C.squads.map(x=>[x[0],x[1]]))}${fun?'':`<div class="field"><span class="field-label">队内位置</span><div class="notice info" style="margin:0">${p.pressure?'抗压位 · 额外倍率 +0.10':'常规位 · 共用 5、6 星抓位池'}</div></div>`}</div>${check(r,'completed','已完成任意结局','','藏品、少人及全追猎通关倍率据此检查')}${fun?'':check(r,'fullHunt','全追猎状态通关','倍率 +0.20','全程不交换探测先锋；每层完成规定追猎作战')}`);
if(!fun)form+=calcSection('02','抓位与策略',`<div class="fields">${selectField(r,'mechanic','机械师策略（须赛前声明）',[['none','未声明 / 无加分'],['ban','禁用机械师 · +400 / 倍率 +0.05'],['outside','仅局外收益 · +100'],['inside','仅局内收益 · +200']])}</div>${check(r,'recruitBonus','满足抓位奖励条件','+300','职业队仅2名六星外援；非职业队遵守各职业六星数量与赛前声明要求')}${check(r,'civilBonus','文明开化：未遇实托邦且通关','+300','仅文明开化分队生效，不含希望的沃土')}${check(r,'box','箱中猎影','+70','在窥视箱进入痛苦将息')}${check(r,'wheel','复得之轮：拒绝 / 整局不触发','+200*')}${check(r,'belly','果腹：拒绝 / 整局不触发','+200*','*两项同时勾选默认合计 +200，见裁判口径')}${check(r,'vine','全程遵守单板藤限制','+200','额外板藤第一时间丢弃，不可出售')}`);
form+=calcSection(fun?'02':'03',fun?'道中追猎':'道中追猎 · 无漏且队内唯一',`<div class="checks">${C.hunts.map(([key,name,f,c])=>check(r,'hunt_'+key,name,'+'+(fun?f:c))).join('')}</div><p class="meta">${fun?'同名关卡只计一次。':'勾选即表示已无漏通关。按赛程顺序自动分配给队内首位达成者，同队重复勾选不重复加分。'}</p>`);
form+=calcSection(fun?'03':'04','结局关卡',`${(fun?[['peace','永无安宁',150,100],['pain','苦痛将息',200,100],['chaos','混沌源阶理论',250,100],['disease','畸症',300,200]]:[['pain','痛苦将息',200,100],['chaos','混沌源阶理论',250,100],['disease','畸症',100,100]]).map(([key,name,v,perfect])=>`<div class="bonus-block">${check(r,key,'通关 '+name,'+'+v)}<div class="subchecks">${check(r,key+'_perfect','无漏通关','+'+perfect,'',key)}${!fun&&['pain','disease'].includes(key)?check(r,key+'_hunt','以全追猎状态通关','+'+(key==='pain'?200:150),'该关卡当时的状态，与最终通关倍率分开判断',key):''}${!fun&&key==='disease'?check(r,'disease_trigger','追猎形式触发（追猎3）','+75','与本关全追猎 +150 互斥，自动取 +150','disease'):''}</div></div>`).join('')}${check(r,'disease_kill','已击杀“玻利瓦尔，症结之核”','+200','按击杀事实计分，可独立于整关通关勾选')}<p class="meta">允许同局多个结局。竞技队内首次痛苦将息与混沌源阶理论另有 +100 团队奖励。</p>`);
if(!fun){form+=calcSection('05','特殊关卡与一般关卡',`<p class="meta">特殊关卡选层即表示满足无漏条件；同名关卡队内只计一次。误入奇境限定项须在相应节点完成。</p><div class="fields">${C.specials.map(s=>selectField(r,'special_'+s.key,s.name+(s.wonder?'（误入奇境）':''),[[0,'未达成'],...Object.entries(s.levels).map(([k,v])=>[k,k+' 层无漏 · +'+v])])).join('')}</div><div class="bonus-block">${check(r,'coexist','通关紧急同域共存','+70')}<div class="subchecks">${check(r,'coexist_black','附带黑流地脉','+70','','coexist')}${check(r,'coexist_hunt','全追猎状态','+50','与黑流地脉同时满足另加 +150','coexist')}${check(r,'coexist_non6','非 6 层通关','+20','','coexist')}</div></div>`);form+=calcSection('06','藏品规则分',`${check(r,'sand','同时持有沙盘 α、β 且通关','+150')}${check(r,'offerings','三供无削且通关','+300','符合所需藏品与调谐仪式“不必依靠外物”条件')}`);}
else{form+=calcSection('04','临时招募与特殊敌人',`<div class="fields">${numberField(r,'temp6','六星临招人数 · 每人 +40',{integer:true})}${numberField(r,'temp5','五星临招人数 · 每人 +15',{integer:true})}${numberField(r,'temp4','四星临招人数 · 每人 +5',{integer:true})}${numberField(r,'animals','鸭 / 狗 / 熊 / 鼠击杀总数 · 每个 +20',{integer:true})}</div>`);form+=calcSection('05','阵营与少人奖励',`<p class="meta">填写各阵营已招募的不同干员数，至少 3 名触发 +400。默认取最高一项。</p><div class="factions">${C.factions.map((name,i)=>`<label class="faction">${name}<input type="number" name="faction_${i}" min="0" max="100" step="1" value="${r['faction_'+i]??0}" aria-label="${name}干员数量"></label>`).join('')}</div>${check(r,'aveAll','Ave Mujica 指定五人全部抓取','改为 +600','还需上方阵营人数至少为 5')}${check(r,'seesAll','S.E.E.S. 指定四人全部抓取','改为 +600','还需上方阵营人数至少为 4')}${check(r,'smallTeam','申请少人通关奖励','(6 − X) × 120')}${numberField(r,'operatorCount','结算页面干员数 X',{integer:true,max:100,hint:'1–5 人且完成任意结局时生效。临招计入，应急助力不计入。'})}`);}
form+=calcSection(fun?'06':'07','裁判复核',`<div class="fields">${!fun&&p.pressure?numberField(r,'violations','D 类违规条数 · 每条 −1000',{integer:true,max:5}):''}${numberField(r,'penalty','其他违规扣分（倍率后）')}${numberField(r,'adjust','裁判调整（倍率后，可为负数）',{min:-10000000})}<div class="field full"><label for="f-adjustReason">调整理由（有调整时必填）</label><input type="text" id="f-adjustReason" name="adjustReason" maxlength="3000" value="${esc(r.adjustReason)}" placeholder="填写规则依据与调整原因"></div><div class="field full"><label for="f-notes">裁判备注 / 录像时间点</label><textarea id="f-notes" name="notes" rows="2" maxlength="3000">${esc(r.notes)}</textarea></div></div>`);
return `<div class="calc-top"><label for="player-select"><strong>当前选手</strong><select id="player-select">${C.players.filter(x=>x.track===track).map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.name}${x.team?' · '+C.teams.find(t=>t.id===x.team).name:''}${x.pressure?' · 抗压位':''}</option>`).join('')}</select></label><div class="actions"><button class="btn secondary small" id="export-json">导出计分 JSON</button><button class="btn secondary small" id="import-button">导入计分</button><input class="sr-only" id="import-file" type="file" accept=".json,application/json" aria-label="选择计分 JSON 文件"></div></div><div class="notice info">本地试算 · 修改只保存于当前浏览器，不会改变已发布成绩。${fun?'娱乐赛道独立计分。':'队内去重需要同队记录齐全，切换选手继续录入即可。'}</div><div class="calc-grid"><form id="calculator-form" novalidate>${form}${policyForm()}<details class="calc-section"><summary>保存与发布正式成绩</summary><div class="publish-help"><p>1. 逐个录入选手，核对队内重复奖励和裁判口径。</p><p>2. 导出 JSON 备份；导入时合并文件内选手记录，同名记录需确认覆盖。</p><p>3. 仓库管理员将导出的 JSON 更新到 <a class="btn secondary small" target="_blank" rel="noopener" href="https://github.com/OneYaYa/OneYaYa.github.io/edit/main/shangwai-cup-3/results.json">GitHub 成绩文件 ↗</a>。GitHub Pages 发布后，所有访客即可在“已发布成绩”查看。</p><p>其他访客无法通过网页计分台修改正式成绩。导出文件会包含全部本地选手的原始录入、备注和裁判口径，请复核后发布。</p><div class="actions"><button type="button" class="btn secondary small" id="copy-official">将已发布记录导入本地</button><button type="button" class="btn secondary small danger" id="clear-player">清空当前选手</button></div></div></details></form><aside class="summary" id="calc-summary" aria-label="计分结果"></aside></div>`;
}
function updateSummary(){const {track}=route(),p=player(selectedPlayer[track]),r=local.records[p.id]||S.fresh(p),w=S.workbook(local.records,local.policy),s=w.scores[p.id],team=w.teams.find(t=>t.id===p.team);if(!$('#calc-summary'))return;$('#calc-summary').innerHTML=`<div class="kicker">SCORE CALCULATOR</div><div class="meta">${esc(p.name)} · 本地试算</div><div class="total" aria-live="polite">${s.entered?fmt(s.total):'待录入'}</div><div class="equation">${p.track==='fun'?`结算分 × 0.8 + 加分 − 扣分`:`（结算分 + 结算加分 − 零件扣分<br> + 关卡分）× 倍率 − 扣分`}</div><div class="breakdown"><div class="line"><span>游戏结算分</span><span>${fmt(s.raw)}</span></div>${p.track==='competitive'?`<div class="line"><span>结算加分</span><span>${s.extra>=0?'+':''}${fmt(s.extra)}</span></div><div class="line"><span>零件扣分</span><span>−${fmt(s.parts)}</span></div>`:''}<div class="line"><span>关卡 / 特殊加分</span><span>+${fmt(s.level)}</span></div><div class="line"><span>${p.track==='fun'?'结算分系数':'总倍率'}</span><span>× ${s.multiplier.toFixed(2)}</span></div><div class="line"><span>倍率后扣分</span><span>−${fmt(s.penalty)}</span></div><div class="line"><span>倍率后奖励 / 调整</span><span>${s.manual+s.afterBonus>=0?'+':''}${fmt(s.manual+s.afterBonus)}</span></div><hr>${team?`<div class="line"><span>团队累计（${team.entered}/3）</span><span>${team.entered?fmt(team.total):'—'}</span></div><div class="line"><span>其中团队首通奖励</span><span>+${team.firstBonus}</span></div><hr>`:''}</div><details ${s.lines.length?'open':''}><summary>逐项计分依据（${s.lines.length}）</summary><div class="detail-lines">${s.lines.map(l=>`<p>${esc(l.label)}<br><strong>${l.value>=0?'+':''}${fmt(l.value)}</strong></p>`).join('')||'勾选达成条件后显示明细。'}</div></details>${s.warnings.length?`<div class="warnings">${s.warnings.map(t=>`<p>${esc(t)}</p>`).join('')}</div>`:''}<a class="btn" href="#${track}/scores" id="view-local">查看本地得分表</a><span class="status-save">${storageMessage}</span>`;}
function render(){const {track,page}=route(),valid=['schedule','rules','scores','calculator'].includes(page)?page:'schedule';$('#main').innerHTML=page==='home'?home():header(track,valid)+`<div class="container content">${({schedule,rules,scores,calculator}[valid])(track)}</div>`;document.title=page==='home'?'上外杯 #3 · 沉沦者的黑流树海':`${track==='fun'?'娱乐赛道':'竞技赛道'} · ${{schedule:'赛程',rules:'规则',scores:'得分',calculator:'计分台'}[valid]} | 上外杯 #3`;if(page==='calculator')updateSummary();}
function download(){const result=S.validate({...local,updatedAt:new Date().toISOString()});const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));a.href=url;a.download='shangwai-cup-3-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出全部本地计分记录。');}
function mergeRecords(data){const d=S.validate(data),overlap=Object.keys(d.records).filter(id=>local.records[id]);if(overlap.length&&!confirm('将覆盖以下选手的本地记录：'+overlap.map(id=>player(id).name).join('、')+'。同时采用导入文件的裁判口径，是否继续？'))return;local.records={...local.records,...d.records};local.policy=d.policy;persist();render();toast('已导入 '+Object.keys(d.records).length+' 位选手的记录。');}
document.addEventListener('click',e=>{
const a=e.target.closest('[data-player]');if(a)selectedPlayer[player(a.dataset.player).track]=a.dataset.player;
const d=e.target.closest('[data-day]');if(d){selectedDay=d.dataset.day;render();}
const t=e.target.closest('[data-team]');if(t){selectedTeam=t.dataset.team;render();}
const r=e.target.closest('[data-rule]');if(r){e.preventDefault();document.getElementById('rule-'+r.dataset.rule)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
const detail=e.target.closest('[data-detail]');if(detail){detailsId=detailsId===detail.dataset.detail?null:detail.dataset.detail;render();if(detailsId)$('.audit')?.scrollIntoView({block:'nearest'});}
if(e.target.closest('#export-json')){e.preventDefault();try{download();}catch(err){toast(err.message);}}
if(e.target.closest('#import-button'))$('#import-file').click();
if(e.target.closest('#view-local'))boardSource='local';
if(e.target.closest('#clear-player')){const p=player(selectedPlayer[route().track]);if(confirm('清空 '+p.name+' 的本地试算记录？已发布成绩不会受影响。')){delete local.records[p.id];persist();render();}}
if(e.target.closest('#copy-official')){if(publicState!=='ready')return toast('已发布数据尚未成功加载。');if(!Object.keys(official.records).length)return toast('目前没有可导入的已发布记录。');try{mergeRecords(official);}catch(err){toast(err.message);}}
});
document.addEventListener('submit',e=>{if(e.target.id==='calculator-form')e.preventDefault();});
document.addEventListener('input',e=>{
const el=e.target;if(!el.closest('#calculator-form')||!el.name)return;
const p=player(selectedPlayer[route().track]);let r=local.records[p.id]||S.fresh(p);
if(el.type==='number'&&!el.validity.valid){el.setAttribute('aria-invalid','true');toast('请输入有效数值；数量需为非负整数。');return;}
el.removeAttribute('aria-invalid');r[el.name]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?(el.name==='base'?'':0):Number(el.value)):el.value;local.records[p.id]=r;
for(const child of document.querySelectorAll('[data-parent]'))child.disabled=!r[child.dataset.parent];
persist();updateSummary();
});
document.addEventListener('change',async e=>{
const el=e.target;
if(el.id==='player-select'){selectedPlayer[route().track]=el.value;render();}
if(el.id==='score-source'){boardSource=el.value;detailsId=null;render();}
if(el.dataset.policy){local.policy[el.dataset.policy]=el.value;persist();updateSummary();toast('裁判口径已更新，整份本地计分已重新计算。');}
if(el.id==='import-file'&&el.files[0]){const f=el.files[0];try{if(f.size>1000000)throw Error('文件过大，请选择小于 1 MB 的计分 JSON。');mergeRecords(JSON.parse(await f.text()));}catch(err){toast('导入失败：'+err.message);}el.value='';}
});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();
fetch('results.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('成绩数据暂不可用');return r.json();}).then(data=>{official=S.validate(data);publicState='ready';if(['scores','schedule'].includes(route().page))render();}).catch(()=>{publicState='error';if(route().page==='scores')render();});
})();
