'use strict';
(()=>{
const C=CUP,S=Scoring,$=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number(x).toLocaleString('zh-CN',{maximumFractionDigits:2});
const KEY='shangwai-cup-3-v1';let local={schemaVersion:1,records:{},policy:{...C.defaultPolicy}},official={schemaVersion:1,records:{},policy:{...C.defaultPolicy}},publicState='loading',selectedDay='2026-09-19',selectedPlayer={fun:'lan',competitive:'mumu'},publicTeam='',storageMessage='修改自动保存于当前浏览器',toastTimer;
try{const saved=localStorage.getItem(KEY);if(saved)local=S.validate(JSON.parse(saved));}catch(e){storageMessage='本地存档无法读取。请先导出或检查浏览器存储设置。';}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4200);}
function persist(){local.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(local));localStorage.setItem(KEY+'-preview','1');storageMessage='已保存到此浏览器 · '+new Date().toLocaleTimeString('zh-CN');}catch(e){storageMessage='浏览器未能保存，请导出 JSON 备份。';}const x=$('.status-save');if(x)x.textContent=storageMessage;}
function player(id){return C.players.find(x=>x.id===id);}
function pAvatar(p){return `<img class="avatar" src="assets/avatars/${esc(p.id)}.jpg" alt="${esc(p.name)}头像" width="50" height="50" decoding="async">`;}
function pIdentity(p){return `<div class="player">${pAvatar(p)}<div><strong>${esc(p.name)} ${p.pressure?'<span class="pill purple">抗压位</span>':''}</strong><small>${p.difficulty} · ${esc(p.squad.endsWith('分队')?p.squad:p.squad+'分队')}</small></div></div>`;}
const isWorkbench=document.body.dataset.page==='workbench';
let rulesTrack='fun';
function route(){const [raw,sub]=location.hash.slice(1).split('/');if(isWorkbench)return {track:raw==='fun'?'fun':'competitive',page:'calculator'};return {track:raw==='fun'?'fun':'competitive',page:'home'};}
function displaySource(){return localStorage.getItem(KEY+'-preview')==='1'?local:official;}
function previewLabel(){return localStorage.getItem(KEY+'-preview')==='1'?'<span class="draft-badge">未发布预览</span>':'';}
function scoreNumber(score){return score.entered?fmt(score.settlement):'—';}
function match(p,w){const sc=w.scores[p.id],team=w.teams.find(t=>t.id===p.team);return `<article class="event-match" data-result-player="${p.id}"><div class="event-match-head">${pIdentity(p)}<span class="track-tag ${p.track}">${p.track==='fun'?'娱乐':'竞技'}</span></div><div class="match-info"><span>${team?esc(team.name):'个人赛'}</span><time datetime="${p.date}T${p.time}:00+08:00">${p.time}</time></div><div class="match-score-pair"><div class="match-score"><span>${p.track==='fun'?'最终得分':'选手结算分'}</span><strong>${scoreNumber(sc)}</strong></div>${team?`<div class="match-score team-addition"><span>团队总加分</span><strong>${team.entered?fmt(team.teamBonus):'—'}</strong></div>`:''}</div>${team&&sc.entered?`<div class="match-contribution">本场团队贡献：${fmt(sc.teamContribution)}（关卡 ${fmt(sc.teamLevel)} / 首通 ${fmt(sc.firstBonus)}）</div>`:''}${sc.entered?`<details class="result-detail"><summary>计分明细</summary>${scoreDetails(p,displaySource().records[p.id]||{},sc)}</details>`:''}</article>`;}
function unifiedSchedule(w){const days=Array.from({length:10},(_,i)=>'2026-09-'+(19+i)),ps=C.players.filter(p=>p.date===selectedDay).sort((a,b)=>a.time.localeCompare(b.time));return `<div class="schedule-panel"><div class="event-dates" role="group" aria-label="比赛日期">${days.map((day,i)=>`<button class="event-date ${day===selectedDay?'active':''}" data-day="${day}" aria-pressed="${day===selectedDay}"><strong>09.${19+i}</strong><span>周${['六','日','一','二','三','四','五'][i%7]}</span></button>`).join('')}</div><div class="day-heading"><h3>${selectedDay.slice(5).replace('-',' / ')}</h3><span>北京时间</span></div><div class="event-matches">${ps.length?ps.map(p=>match(p,w)).join(''):'<div class="empty">当日无比赛</div>'}</div></div>`;}
function depositPanel(t){const capacity=200+t.depositBonus,ratio=Math.max(0,Math.min(100,t.depositRemaining/capacity*100));return `<section class="deposit-panel${t.depositRemaining<0?' overdrawn':''}" aria-label="团队存款"><div class="deposit-heading"><span>团队剩余存款</span><span class="deposit-total">额度 ${fmt(capacity)}</span></div><div class="deposit-balance"><strong data-deposit="remaining">${fmt(t.depositRemaining)}</strong><span>存款</span></div><div class="deposit-meter" role="meter" aria-label="剩余存款比例" aria-valuemin="0" aria-valuemax="${capacity}" aria-valuenow="${Math.max(0,t.depositRemaining)}"><i style="width:${ratio}%"></i></div><div class="deposit-stats"><span>累计提取 <b data-deposit="used">${fmt(t.depositUsed)}</b></span><span>培育增加 <b>+${fmt(t.depositBonus)}</b></span></div><div class="deposit-people">${t.withdrawals.map(r=>`<div class="deposit-person"><span>${esc(player(r.id).name)}</span><span class="deposit-person-value"><small>提取</small><b>${fmt(r.withdrawn)}</b>${r.bonus?`<em>+${fmt(r.bonus)}</em>`:''}</span></div>`).join('')}</div>${t.depositRemaining<0?'<p class="notice">累计提取已超出团队存款，请核对记录。</p>':''}</section>`;}

function teams(w){return `<a class="competitive-poster" href="assets/competitive-poster.png?v=20260917-4" target="_blank" rel="noopener" aria-label="查看竞技团队赛完整海报"><img src="assets/competitive-poster.png?v=20260917-4" alt="上外杯 #3 竞技团队赛：多边卖鸭分队对阵cornhub，N15，2026年9月20日至28日" width="1774" height="887" loading="lazy" decoding="async"></a><div class="event-teams">${w.teams.map((t,i)=>`<article class="event-team" data-result-team="${t.id}"><div class="team-cover team-cover-${i}"><span class="team-number">0${i+1}</span><h3>${esc(t.name)}</h3><div class="team-cover-avatars">${t.members.map(id=>pAvatar(player(id))).join('')}</div></div><div class="team-score-heading"><span>团队总分</span><strong>${t.entered?fmt(t.total):'—'}</strong></div><div class="team-score-pair"><div class="score-metric"><span>选手结算分合计</span><strong>${t.entered?fmt(t.settlementTotal):'—'}</strong></div><div class="score-metric team-addition"><span>团队总加分</span><strong>${t.entered?fmt(t.teamBonus):'—'}</strong></div></div><div class="team-members">${t.members.map(id=>{const p=player(id),sc=w.scores[id];return `<div class="team-member">${pIdentity(p)}<div class="member-result"><span>选手结算分</span><strong>${scoreNumber(sc)}</strong><time>${p.date.slice(5).replace('-','.')} ${p.time}</time></div></div>`}).join('')}</div>${depositPanel(t)}<details class="team-bonus-details"><summary>团队总加分明细</summary>${t.members.map(id=>`<div class="line"><span>${esc(player(id).name)} · 关卡分</span><b>${w.scores[id].entered?fmt(w.scores[id].teamLevel):'—'}</b></div>`).join('')}${t.members.flatMap(id=>w.scores[id].lines.filter(l=>l.kind==='first').map(l=>`<div class="line"><span>${esc(player(id).name)} · ${esc(l.label)}</span><b>+${l.value}</b></div>`)).join('')}</details><button type="button" class="team-data-open" data-public-team="${t.id}" aria-expanded="${publicTeam===t.id}">${publicTeam===t.id?'收起团队数据':'查看团队数据'}</button></article>`).join('')}</div>${publicTeamDashboard(w)}`;}
function sectionTitle(n,title,extra=''){return `<div class="event-heading"><span>${n}</span><h2>${title}</h2><i></i>${extra}</div>`;}
function home(){const source=displaySource(),w=S.workbook(source.records,source.policy);return `<section class="home-hero"><h1 class="sr-only">上外杯 #3 · 沉沦者的黑流树海</h1><img class="poster" src="assets/poster-multilingual.png" alt="上外杯 #3 多语种主题海报：沉沦者的黑流树海，英语、法语、西班牙语与日语设计译文，2026年9月19日至28日" width="1774" height="887"></section><div class="event-container"><section id="schedule" class="event-section">${sectionTitle('01','赛程规划',previewLabel())}${unifiedSchedule(w)}</section><section id="teams" class="event-section">${sectionTitle('02','分队',previewLabel())}${teams(w)}</section><section id="rules" class="event-section">${sectionTitle('03','赛事规则')}<div class="rules-switch" role="group" aria-label="规则赛道"><button data-rules-track="fun" class="${rulesTrack==='fun'?'active':''}" aria-pressed="${rulesTrack==='fun'}">娱乐赛道</button><button data-rules-track="competitive" class="${rulesTrack==='competitive'?'active':''}" aria-pressed="${rulesTrack==='competitive'}">竞技赛道</button></div><div class="event-rules">${rules(rulesTrack)}</div></section></div>`;}
function workbenchHeader(track){return `<div class="workbench-heading"><div><span class="kicker">SISU CUP 3</span><h1>记分工作台</h1></div><a class="btn secondary" href="index.html#schedule" target="_blank" rel="noopener">查看赛事展示 ↗</a></div><nav class="rules-switch" aria-label="记分赛道"><a href="#fun" class="${track==='fun'?'active':''}">娱乐赛道</a><a href="#competitive" class="${track==='competitive'?'active':''}">竞技赛道</a></nav>`;}

function bossReward(r,key){if(!r)return 0;if(key==='pain')return r.pain?200+(r.pain_perfect?100:0)+(r.pain_hunt?200:0):0;if(key==='chaos')return r.chaos?250+(r.chaos_perfect?100:0):0;if(key==='disease')return (r.disease?100+(r.disease_perfect?100:0)+(r.disease_hunt?150:r.disease_trigger?75:0):0)+(r.disease_kill?200:0);return 0;}
function achievement(label,score,owner='',note=''){return `<div class="team-achievement ${score?'done':'pending'}"><span>${esc(label)}</span><strong>${score?'+'+fmt(score):'未达成'}</strong>${owner?`<small>${esc(owner)}${note?' · '+esc(note):''}</small>`:''}</div>`;}
function teamDataMarkup(w,t,records){const members=t.members.map(player);
 const completed=members.filter(p=>records[p.id]?.completed).length,fullHunt=members.filter(p=>records[p.id]?.completed&&records[p.id]?.fullHunt).length,restarts=members.reduce((n,p)=>n+Number(records[p.id]?.restartCount||0),0),calls=members.reduce((n,p)=>n+Number(records[p.id]?.callCount||0),0),overdraft=members.filter(p=>records[p.id]?.overdraftUsed).length;
 const bossNames={pain:'痛苦将息',chaos:'混沌源阶理论',disease:'畸症'};
 const bosses=Object.entries(bossNames).map(([key,name])=>{const id=w.bossOwners[t.id+':'+key],first=w.firstOwners[t.id+':'+key],score=id?bossReward(records[id],key):0;return `<div class="team-boss ${score?'done':''}"><div><span>${name}</span><strong>${score?'+'+fmt(score):'未通关'}</strong></div>${id?`<small>最高奖励 · ${esc(player(id).name)}</small>`:''}${first?`<small>首通奖励 · ${esc(player(first).name)} +100</small>`:''}</div>`}).join('');
 const hunts=C.hunts.map(([key,name,,score])=>{const id=w.owners[t.id+':hunt_'+key];return achievement(name,id?score:0,id?player(id).name:'','无漏')}).join('');
 const specials=C.specials.map(item=>{const id=w.owners[t.id+':special_'+item.key],layer=id?Number(records[id]?.['special_'+item.key]||0):0;return achievement(item.name,id&&item.levels[layer]?item.levels[layer]:0,id?player(id).name:'',layer?layer+' 层':'')}).join('');
 const memberRows=members.map(p=>{const r=records[p.id]||{},sc=w.scores[p.id];return `<article class="team-data-player"><div>${pIdentity(p)}</div><dl><div><dt>选手结算分</dt><dd>${sc.entered?fmt(sc.settlement):'—'}</dd></div><div><dt>团队贡献</dt><dd>${sc.entered?fmt(sc.teamContribution):'—'}</dd></div><div><dt>提取存款</dt><dd>${fmt(r.withdrawn||0)}</dd></div></dl></article>`}).join('');
 return `<section class="team-data"><div class="team-data-title"><div><span class="kicker">TEAM DATA</span><h2>${esc(t.name)}</h2></div><div class="team-data-score"><span>团队总分</span><strong>${t.entered?fmt(t.total):'—'}</strong></div></div><div class="team-data-stats"><div><strong>${t.entered}/${t.members.length}</strong><span>结算已录入</span></div><div><strong>${completed}/${t.members.length}</strong><span>完成任意结局</span></div><div><strong>${fullHunt}</strong><span>全追猎通关</span></div><div class="${restarts>2?'alert':''}"><strong>${restarts}/2</strong><span>额外重开</span></div><div class="${calls>3?'alert':''}"><strong>${calls}/3</strong><span>连麦次数</span></div><div class="${overdraft>1?'alert':''}"><strong>${overdraft}/1</strong><span>超取权使用</span></div><div class="deposit-stat ${t.depositRemaining<0?'alert':''}"><strong>${fmt(t.depositRemaining)}</strong><span>剩余存款</span></div></div><div class="team-data-section"><h3>选手概览</h3><div class="team-data-players">${memberRows}</div></div><div class="team-data-section"><h3>BOSS 结局</h3><div class="team-bosses">${bosses}</div></div><div class="team-data-section"><h3>道中追猎 <small>无漏且队内同名一次</small></h3><div class="team-achievements">${hunts}</div></div><div class="team-data-section"><h3>特殊关卡 <small>无漏且队内同名一次</small></h3><div class="team-achievements">${specials}</div></div><div class="team-data-section"><h3>团队存款</h3>${depositPanel(t)}</div></section>`;}
function publicTeamDashboard(w){if(!publicTeam)return '';const t=w.teams.find(x=>x.id===publicTeam);if(!t)return '';return `<div class="public-team-data-wrap" id="public-team-data"><div class="public-team-data-toolbar"><span>公开团队数据</span><button type="button" class="btn secondary small" data-public-team="${t.id}">收起</button></div>${teamDataMarkup(w,t,displaySource().records)}</div>`;}


const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const rule=(id,title,body)=>`<section class="rule-section" id="rule-${id}"><h3>${title}</h3>${body}</section>`;
function rules(track){const fun=track==='fun';const sections=[];
sections.push(['start','参赛与开局',`<p>在集成战略“沉沦者的黑流树海”中进行比赛。${fun?'娱乐赛道可以自行选择难度。':'竞技赛道统一 N15，参与 D 类三人团队赛。'}</p><ul><li>无襁褓开局，可自行选择特定的开局奖励。</li><li>开始时进度不得超过初始招募；随心所欲开局应停留在初始招募组合选择界面。</li><li>赛程采用提供截图中的拟定比赛时间，均按北京时间展示。</li></ul>`]);
sections.push(['formula','基础计分',fun?'<div class="formula">个人最终分 = 个人结算分 × 0.8 + 关卡规则分</div><p>本页将道中、结局、临招、特殊敌人、阵营和少人奖励归入加分项。</p>':`<div class="formula">选手结算分 =（游戏结算分 − 7.5 × 零件数 + 特别加分）× 总倍率 − 违规扣分<br>本场团队关卡分 = 第 6 节关卡奖励（队内去重、同名 Boss 取最高，不乘个人倍率）<br>团队总加分 = 各场有效团队关卡分之和 + 首次结局奖励<br>团队总分 = 选手结算分合计 + 团队总加分<br>总倍率 = 分队系数 + 全追猎通关系数 + 机械师禁用系数 + 抗压位系数</div>${table(['分队 / 条件','系数'],[['多边贸易','0.85'],['文明开化 / 地面突破 / 高台突破','1.10'],['其余分队','1.00'],['全追猎状态通关','额外 +0.20'],['赛前声明禁用机械师','额外 +0.05'],['D 类抗压位','额外 +0.10']])}<p>文明开化分队通关且全程未遇实托邦（不含希望的沃土）：结算分 +300。</p>`]);
sections.push(['hunt','追猎与结局',`${table(['道中追猎关卡',fun?'加分（同名一次）':'无漏加分（队内一次）'],C.hunts.map(x=>[x[1],'+'+x[fun?2:3]]))}<p>${fun?'娱乐赛道的道中追猎奖励按个人同名关卡一次计算。':'同队同名 Boss 取单名选手完整奖励的最高值，各 Boss 分别比较；同分按赛程先后归属。全追猎状态：不交换探测先锋，且进入节点或通过关卡前每层均进行非“不期而遇”出现的追猎作战。小八界传至偏安一隅不破坏状态。'}</p>${table(['结局关卡','基础','无漏','额外条件'],fun?[['永无安宁','150','100','—'],['苦痛将息','200','100','—'],['混沌源阶理论','250','100','—'],['畸症','300','200','击杀症结之核 +200']]:[['痛苦将息','200','100','全追猎状态通关 +200'],['混沌源阶理论','250','100','—'],['畸症','100','100','击杀症结之核 +200；全追猎 +150，或追猎3 +75（两者互斥）']])}`]);
if(fun){sections.push(['special','娱乐特殊加分',`<ul><li>临时招募：每名六星 +40、五星 +15、四星 +5。</li><li>每击杀一个鸭 / 狗 / 熊 / 鼠，+20。</li><li>以下阵营至少 3 名干员可获得 +400：${C.factions.join('、')}。</li><li>Ave Mujica 五人齐全（丰川祥子、三角初华、若叶睦、八幡海铃、祐天寺若麦），对应奖励改为 +600。</li><li>S.E.E.S. 四人齐全（结城理、岳羽由加莉、埃癸斯、虎狼丸），对应奖励改为 +600。</li><li>完成任意结局，结算页面不超过 5 位干员：+(6 − X) × 120。临招计入 X，应急助力不计入。</li></ul><p>多个达标阵营分别累加；同一阵营的完整组合奖励替代其基础奖励。</p>`]);}
else{
sections.push(['recruit','抓位与机械师',`<ul><li>职业队仅抓取 2 名六星外援：结算分 +300。职业队为突击战术、破坏战术、堡垒战术、远程战术分队。</li><li>非职业队每职业仅抓取 1 名六星，可赛前声明一个职业放宽为 2 名：满足条件结算分 +300。</li><li>机械师必须赛前声明选项：禁用 +400 且倍率 +0.05；仅局外收益 +100；仅局内收益 +200。三者互斥。</li><li>禁用机械师时，“后备精通 I”带来的开局一次应急助力仍可使用。</li><li>仅局外：不将机械师编入编队；仅局内：不使用容量 +2 与结构性原理。</li></ul>`]);
sections.push(['special','特殊关卡与藏品',`${table(['无漏关卡（队内同名一次）','层数与分数'],C.specials.map(s=>[s.name+(s.wonder?' · 误入奇境限定':''),Object.entries(s.levels).map(([k,v])=>k+'层 +'+v).join(' / ')]))}<ul><li>紧急同域共存：+70；黑流地脉 +70；全追猎状态 +50；非 6 层 +20；黑流地脉与全追猎同时满足，额外 +150。</li><li>在窥视箱进入痛苦将息（箱中猎影）：团队关卡分 +70，无需在 6 层进入调和仪式。</li><li>同时持有沙盘 α 与 β 且通关：+150。</li><li>三供无削：同时持有所需三供藏品或源私钥，在调谐仪式选择“不必依靠外物”且通关，+300。完整措辞见原文。</li><li>遇到复得之轮 / 果腹不抓取，或不可抗力获得但全局不触发效果：结算分 +200。两件分别计分，均满足时合计 +400。</li><li>零件箱全局遵守单板藤限制，额外板藤第一时间无条件丢弃（不得出售）：结算分 +200。</li></ul>`]);
sections.push(['team','D 类团队规则',`<p>本届采用 <strong>3 名竞技选手</strong> 的 D 类配置。</p><ul><li>全队存款 200。“生命游戏—瘤胃”的存款 +5 不计入。用种子培育出襁褓，团队存款 +5。</li><li>全队一次超取权：可在一个商店内吸满 12 块，不计入全队存款。</li><li>全队最多 2 次、每人最多 1 次额外重开：在进入 II 层未移动前使用，可再次烧取指定开局；不重置取款与超取权。</li><li>两名非抗压位共用 5、6 星抓位池（全 5、6 星限 1），抗压位独立使用一个池子。</li><li>应急助力、临时招募不占队内池子。竞技不限时长，无速通、额外藏品、临招或隐藏分；明确列出的藏品规则分仍按竞技规则计算。</li><li>连麦最多 3 次，每次 3 分钟，可连续使用，使用前与工作人员沟通。</li><li>队内首次通关痛苦将息 +100，首次通关混沌源阶理论 +100，自动按赛程顺序归属首通选手，仅计入团队总加分，不计入选手结算分。</li></ul><h3>抗压位的五项限制</h3><ol><li>前两位选手开局主力六星全程禁用。</li><li>全程最多抓取 2 名五星。</li><li>进入卡德霍之颅前获得“焚毁‘文明’”。</li><li>初始种子不可种植、不可在一层商店售出。</li><li>不可交换探测先锋。</li></ol><p>每违反一条 −1000；抗压位全追猎仍是可选项。违规在倍率计算后扣除。</p>`]);
}
return `<div class="sourcebar"><a class="btn secondary small" href="rules/${track}.docx" download>下载${fun?'娱乐':'竞技'}规则原文</a>${!fun?'<a class="btn secondary small" href="rules/team.docx" download>下载团队规则原文</a>':''}</div><div class="rule-layout"><aside class="rule-nav" aria-label="规则目录">${sections.map(([id,title])=>`<a href="#rule-${id}" data-rule="${id}">${title}</a>`).join('')}</aside><div>${sections.map(([id,title,body])=>rule(id,title,body)).join('')}<details class="rule-section"><summary>查看原始${fun?'娱乐':'竞技'}规则全文（含历史更新）</summary><div class="raw-rule">${esc(RULE_SOURCES[track])}</div></details>${!fun?`<details class="rule-section"><summary>查看团队规则全文（含历史 A / B / C 配置）</summary><div class="raw-rule">${esc(RULE_SOURCES.team)}</div></details>`:''}</div></div>`;}
function scoreDetails(p,r,score){return `<div class="audit"><strong>${esc(p.name)} · 计分明细</strong><div class="formula">${p.track==='fun'?`${fmt(score.raw)} × 0.8 + ${fmt(score.level)} − ${fmt(score.penalty)} + ${fmt(score.manual)} = ${fmt(score.settlement)}`:`选手结算分：(${fmt(score.raw)} + ${fmt(score.extra)} − ${fmt(score.parts)}) × ${score.multiplier} − ${fmt(score.penalty)} + ${fmt(score.manual)} = ${fmt(score.settlement)}<br>团队关卡分：${fmt(score.teamLevel)}；本人首通奖励：${fmt(score.firstBonus)}`}</div>${score.lines.map(l=>`<div class="line"><span>${p.track==='competitive'?(l.kind==='base'?'特别加分 · ':l.kind==='first'?'团队首通 · ':'团队关卡 · '):''}${esc(l.label)}</span><b>${l.value>=0?'+':''}${fmt(l.value)}</b></div>`).join('')}${score.warnings.map(w=>`<p class="notice">${esc(w)}</p>`).join('')}${r.adjustReason?`<p>调整说明：${esc(r.adjustReason)}</p>`:''}${r.notes?`<p>裁判备注：${esc(r.notes)}</p>`:''}</div>`;}
function numberField(r,key,title,{integer=false,hint='',max=10000000,min=0}={}){return `<div class="field"><label for="f-${key}">${title}</label><input id="f-${key}" name="${key}" type="number" inputmode="decimal" value="${esc(r[key]??'')}" min="${min}" max="${max}" step="${integer?1:'any'}" ${key==='base'?'placeholder="输入游戏结算分"':''}>${hint?`<small>${hint}</small>`:''}</div>`;}
function check(r,key,title,bonus='',hint='',parent=''){return `<label class="check"><input type="checkbox" name="${key}" ${r[key]?'checked':''} ${parent?`data-parent="${parent}" ${!r[parent]?'disabled':''}`:''}><span class="check-label">${title}${hint?`<small>${hint}</small>`:''}</span>${bonus?`<span class="bonus">${bonus}</span>`:''}</label>`;}
function selectField(r,key,title,options){return `<div class="field"><label for="f-${key}">${title}</label><select name="${key}" id="f-${key}">${options.map(([v,l])=>`<option value="${v}" ${String(r[key]??0)===String(v)?'selected':''}>${l}</option>`).join('')}</select></div>`;}
function calcSection(n,title,body){return `<section class="calc-section"><h3><span class="step">${n}</span>${title}</h3>${body}</section>`;}
function policyForm(){return `<details class="calc-section"><summary>已确认计分规则</summary><ul><li>娱乐阵营奖励分别累加。</li><li>复得之轮、果腹分别 +200，可合计 +400。</li><li>所有违规在倍率计算后扣除。</li><li>首次结局奖励仅计入团队总加分，不进入个人结算分，也不乘个人倍率。</li></ul></details>`;}
function calculator(track){const p=player(selectedPlayer[track]),r=local.records[p.id]||S.fresh(p),fun=track==='fun';let form='';
if(!fun)form+='<h2 class="ledger-heading">选手结算记录</h2>';
form+=calcSection('01','基础记录',`<div class="fields">${numberField(r,'base','游戏结算分')}${fun?'':numberField(r,'parts','零件数量',{integer:true,hint:'每个零件扣除 7.5 分'})}${fun?'':selectField(r,'squad','使用分队',C.squads.map(x=>[x[0],x[1]]))}${fun?'':`<div class="field"><span class="field-label">队内位置</span><div class="notice info" style="margin:0">${p.pressure?'抗压位 · 额外倍率 +0.10':'常规位 · 共用 5、6 星抓位池'}</div></div>`}</div>${fun?check(r,'completed','已完成任意结局','','藏品与少人奖励据此检查'):''}`);
if(!fun)form+=calcSection('02','团队数据录入',`<p class="team-input-note"><strong>当前记录：${esc(p.name)}</strong><span>填写“游戏结算分”后，主页自动计为 1 名结算已录入选手。以下项目会按队伍自动汇总。</span></p><div class="team-input-checks">${check(r,'completed','本选手完成任意结局','','计入主页“完成任意结局”人数')}${check(r,'fullHunt','本选手以全追猎状态通关','倍率 +0.20','计入主页“全追猎通关”人数')}</div><div class="fields team-resource-fields">${numberField(r,'restartCount','本选手额外重开次数',{integer:true,max:1,hint:'每位选手最多 1 次，全队最多 2 次。'})}${numberField(r,'callCount','本选手连麦次数',{integer:true,max:3,hint:'全队最多 3 次，每次最多 3 分钟。'})}${numberField(r,'withdrawn','本选手累计提取存款',{integer:true,hint:'仅填写占用团队额度的累计提取量；超取权及生命游戏—瘤胃的 +5 不计入。'})}${numberField(r,'swaddles','本选手培育襁褓次数',{integer:true,hint:'每次为团队增加 5 存款。'})}</div>${check(r,'overdraftUsed','本选手使用了团队超取权','','全队仅 1 次；该商店吸满 12 块，不计入团队存款')}`);
if(!fun)form+=calcSection('03','抓位与策略',`<div class="fields">${selectField(r,'mechanic','机械师策略（须赛前声明）',[['none','未声明 / 无加分'],['ban','禁用机械师 · +400 / 倍率 +0.05'],['outside','仅局外收益 · +100'],['inside','仅局内收益 · +200']])}</div>${check(r,'recruitBonus','满足抓位奖励条件','+300','职业队仅2名六星外援；非职业队遵守各职业六星数量与赛前声明要求')}${check(r,'civilBonus','文明开化：未遇实托邦且通关','+300','仅文明开化分队生效，不含希望的沃土')}${check(r,'wheel','复得之轮：拒绝 / 整局不触发','+200')}${check(r,'belly','果腹：拒绝 / 整局不触发','+200','两项分别计分，同时满足合计 +400')}${check(r,'vine','全程遵守单板藤限制','+200','额外板藤第一时间丢弃，不可出售')}`);
if(!fun)form+=calcSection('04','藏品特别加分',`${check(r,'sand','同时持有沙盘 α、β 且通关','+150')}${check(r,'offerings','三供无削且通关','+300','符合所需藏品与调谐仪式“不必依靠外物”条件')}`);
if(!fun)form+='<h2 class="ledger-heading">团队关卡记录</h2><p class="meta">记录当前选手达成的关卡，队内去重、同名 Boss 取最高后汇入团队总加分，不乘个人倍率。</p>';
form+=calcSection(fun?'02':'05',fun?'道中追猎':'道中追猎 · 无漏且队内唯一',`<div class="checks">${C.hunts.map(([key,name,f,c])=>check(r,'hunt_'+key,name,'+'+(fun?f:c))).join('')}</div><p class="meta">${fun?'同名关卡只计一次。':'勾选即表示已无漏通关。按赛程顺序自动分配给队内首位达成者，同队重复勾选不重复加分。'}</p>`);
form+=calcSection(fun?'03':'06','结局关卡',`${(fun?[['peace','永无安宁',150,100],['pain','苦痛将息',200,100],['chaos','混沌源阶理论',250,100],['disease','畸症',300,200]]:[['pain','痛苦将息',200,100],['chaos','混沌源阶理论',250,100],['disease','畸症',100,100]]).map(([key,name,v,perfect])=>`<div class="bonus-block">${check(r,key,'通关 '+name,'+'+v)}<div class="subchecks">${check(r,key+'_perfect','无漏通关','+'+perfect,'',key)}${!fun&&['pain','disease'].includes(key)?check(r,key+'_hunt','以全追猎状态通关','+'+(key==='pain'?200:150),'该关卡当时的状态，与最终通关倍率分开判断',key):''}${!fun&&key==='disease'?check(r,'disease_trigger','追猎形式触发（追猎3）','+75','与本关全追猎 +150 互斥，自动取 +150','disease'):''}</div></div>`).join('')}${check(r,'disease_kill','已击杀“玻利瓦尔，症结之核”','+200','按击杀事实计分，可独立于整关通关勾选')}<p class="meta">${fun?'允许同局多个结局。':'同队同名 Boss 取单名选手完整奖励的最高值，不拼接不同选手的条件。允许同局多个结局。队内首次痛苦将息与混沌源阶理论各 +100，自动归属首通选手的团队贡献明细。'}</p>`);
if(!fun){form+=calcSection('07','特殊关卡与一般关卡',`${check(r,'box','箱中猎影','+70','在窥视箱进入痛苦将息')}<p class="meta">特殊关卡选层即表示满足无漏条件；同名关卡队内只计一次。误入奇境限定项须在相应节点完成。</p><div class="fields">${C.specials.map(s=>selectField(r,'special_'+s.key,s.name+(s.wonder?'（误入奇境）':''),[[0,'未达成'],...Object.entries(s.levels).map(([k,v])=>[k,k+' 层无漏 · +'+v])])).join('')}</div><div class="bonus-block">${check(r,'coexist','通关紧急同域共存','+70')}<div class="subchecks">${check(r,'coexist_black','附带黑流地脉','+70','','coexist')}${check(r,'coexist_hunt','全追猎状态','+50','与黑流地脉同时满足另加 +150','coexist')}${check(r,'coexist_non6','非 6 层通关','+20','','coexist')}</div></div>`);}
else{form+=calcSection('04','临时招募与特殊敌人',`<div class="fields">${numberField(r,'temp6','六星临招人数 · 每人 +40',{integer:true})}${numberField(r,'temp5','五星临招人数 · 每人 +15',{integer:true})}${numberField(r,'temp4','四星临招人数 · 每人 +5',{integer:true})}${numberField(r,'animals','鸭 / 狗 / 熊 / 鼠击杀总数 · 每个 +20',{integer:true})}</div>`);form+=calcSection('05','阵营与少人奖励',`<p class="meta">填写各阵营已招募的不同干员数，至少 3 名触发 +400。各达标阵营分别累加。</p><div class="factions">${C.factions.map((name,i)=>`<label class="faction">${name}<input type="number" name="faction_${i}" min="0" max="100" step="1" value="${r['faction_'+i]??0}" aria-label="${name}干员数量"></label>`).join('')}</div>${check(r,'aveAll','Ave Mujica 指定五人全部抓取','改为 +600','还需上方阵营人数至少为 5')}${check(r,'seesAll','S.E.E.S. 指定四人全部抓取','改为 +600','还需上方阵营人数至少为 4')}${check(r,'smallTeam','申请少人通关奖励','(6 − X) × 120')}${numberField(r,'operatorCount','结算页面干员数 X',{integer:true,max:100,hint:'1–5 人且完成任意结局时生效。临招计入，应急助力不计入。'})}`);}
form+=calcSection(fun?'06':'08','裁判复核',`<div class="fields">${!fun&&p.pressure?numberField(r,'violations','D 类违规条数 · 每条 −1000',{integer:true,max:5}):''}${numberField(r,'penalty','其他违规扣分（倍率后）')}${numberField(r,'adjust','裁判调整（倍率后，可为负数）',{min:-10000000})}<div class="field full"><label for="f-adjustReason">调整理由（有调整时必填）</label><input type="text" id="f-adjustReason" name="adjustReason" maxlength="3000" value="${esc(r.adjustReason)}" placeholder="填写规则依据与调整原因"></div><div class="field full"><label for="f-notes">裁判备注 / 录像时间点</label><textarea id="f-notes" name="notes" rows="2" maxlength="3000">${esc(r.notes)}</textarea></div></div>`);
return `<div class="calc-top"><label for="player-select"><strong>当前选手</strong><select id="player-select">${C.players.filter(x=>x.track===track).map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.name}${x.team?' · '+C.teams.find(t=>t.id===x.team).name:''}${x.pressure?' · 抗压位':''}</option>`).join('')}</select></label><div class="actions"><button class="btn secondary small" id="export-json">导出计分 JSON</button><button class="btn secondary small" id="import-button">导入计分</button><input class="sr-only" id="import-file" type="file" accept=".json,application/json" aria-label="选择计分 JSON 文件"></div></div><div class="notice info">录入结果即时同步至本机赛事展示；点击“发布成绩”更新所有访客看到的成绩。${fun?'娱乐赛道独立计分。':'队内去重需要同队记录齐全，切换选手继续录入即可。'}</div><div class="calc-grid"><form id="calculator-form" novalidate>${form}${policyForm()}<details class="calc-section"><summary>记录管理</summary><div class="actions"><button type="button" class="btn secondary small" id="copy-official">导入已发布记录</button><button type="button" class="btn secondary small danger" id="clear-player">清空当前选手</button></div></details>${publicationPanel()}</form><aside class="summary" id="calc-summary" aria-label="计分结果"></aside></div>`;
}
function updateSummary(){const {track}=route(),p=player(selectedPlayer[track]),w=S.workbook(local.records,local.policy),s=w.scores[p.id],team=w.teams.find(t=>t.id===p.team);if(!$('#calc-summary'))return;$('#calc-summary').innerHTML=`<div class="meta">${esc(p.name)} · 本地记分</div><div class="summary-scores" aria-live="polite"><div class="score-metric"><span>${team?'选手结算分':'最终得分'}</span><strong data-summary="settlement">${s.entered?fmt(s.settlement):'待录入'}</strong></div>${team?`<div class="score-metric team-addition"><span>团队总加分</span><strong data-summary="team-bonus">${team.entered?fmt(team.teamBonus):'—'}</strong></div>`:''}</div><div class="equation">${team?'团队总分 = 选手结算分合计 + 团队总加分':'游戏结算分 × 0.8 + 加分 − 扣分'}</div>${team?depositPanel(team):''}<div class="breakdown"><div class="line"><span>游戏结算分</span><span>${fmt(s.raw)}</span></div>${team?`<div class="line"><span>特别加分</span><span>+${fmt(s.extra)}</span></div><div class="line"><span>零件扣分</span><span>−${fmt(s.parts)}</span></div>`:''}<div class="line"><span>${team?'本场关卡原始分':'关卡 / 特殊加分'}</span><span>+${fmt(s.level)}</span></div><div class="line"><span>倍率</span><span>× ${s.multiplier.toFixed(2)}</span></div><div class="line"><span>倍率后违规扣分</span><span>−${fmt(s.penalty)}</span></div><div class="line"><span>裁判调整</span><span>${fmt(s.manual)}</span></div>${team?`<hr><div class="line"><span>本场团队关卡分</span><strong data-summary="team-level">${s.entered?fmt(s.teamLevel):'—'}</strong></div><div class="line"><span>团队关卡分累计</span><span>${fmt(team.levelTotal)}</span></div><div class="line"><span>团队首次结局奖励</span><span>+${team.firstBonus}</span></div><div class="line"><span>选手结算分合计</span><span>${fmt(team.settlementTotal)}</span></div><div class="line"><span>团队总分</span><strong>${team.entered?fmt(team.total):'—'}</strong></div>`:''}</div>${['base','rule','first'].map(kind=>{const lines=s.lines.filter(l=>l.kind===kind);return lines.length?`<details open><summary>${team?(kind==='base'?'个人特别加分':kind==='first'?'本人团队首通奖励':'团队关卡项'):'加分明细'}</summary><div class="detail-lines">${lines.map(l=>`<p>${esc(l.label)}<br><strong>+${fmt(l.value)}</strong></p>`).join('')}</div></details>`:'';}).join('')}${s.warnings.length?`<div class="warnings">${s.warnings.map(t=>`<p>${esc(t)}</p>`).join('')}</div>`:''}<a class="btn" href="index.html#schedule" target="_blank" rel="noopener">查看赛事展示 ↗</a><span class="status-save">${storageMessage}</span>`;}
function publicationPanel(){return `<section class="calc-section"><h3>发布成绩</h3><p>发布后，赛程个人成绩与分队总分同步更新。发布需要授权写入赛事仓库。</p><label for="publish-token">GitHub 访问令牌</label><input id="publish-token" type="password" autocomplete="off" spellcheck="false" placeholder="仅用于本次发布，不保存"><div class="actions publish-actions"><button type="button" class="btn" id="publish-results">发布成绩</button><button type="button" class="btn secondary" id="official-preview">查看已发布版本</button></div><p id="publish-status" role="status"></p></section>`;}
function stable(value){if(Array.isArray(value))return JSON.stringify(value.map(x=>JSON.parse(stable(x))));if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stable(value[k])).join(',')+'}';return JSON.stringify(value);}
function scoreContent(value){return stable({records:value.records,policy:value.policy});}
let publishing=false;
async function publishResults(){
 if(publishing)return;
 const input=$('#publish-token'),token=input.value.trim();input.value='';
 if(!token)return toast('请在工作台输入具有此仓库 Contents 读写权限的 GitHub 令牌。');
 let snapshot;try{snapshot=S.validate({...local,records:{...official.records,...local.records},updatedAt:new Date().toISOString()});for(const r of Object.values(snapshot.records))if(r.adjust&&!r.adjustReason.trim())throw Error('请为裁判调整填写理由。');}catch(e){return toast(e.message);}
 if(!Object.keys(snapshot.records).length)return toast('请先录入至少一项赛事数据。');
 publishing=true;const button=$('#publish-results');button.disabled=true;const status=$('#publish-status');status.textContent='正在核对并发布…';
 const endpoint='https://api.github.com/repos/OneYaYa/shangwai-cup-3/contents/results.json',headers={Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};
 try{
  const response=await fetch(endpoint+'?ref=main',{headers,cache:'no-store'});if(!response.ok)throw Error(response.status===401||response.status===403?'令牌无效或缺少仓库写入权限。':'无法读取线上成绩（'+response.status+'）。');
  const file=await response.json();const remote=S.validate(JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(file.content.replace(/\s/g,'')),c=>c.charCodeAt(0)))));
  if(publicState!=='ready'||scoreContent(remote)!==scoreContent(official))throw Error('线上成绩已有更新。请刷新工作台并导入已发布记录，核对后重新发布。');
  const text=JSON.stringify(snapshot,null,2)+'\n',content=btoa(Array.from(new TextEncoder().encode(text),b=>String.fromCharCode(b)).join(''));
  const result=await fetch(endpoint,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({message:'Publish SISU CUP 3 results',content,sha:file.sha,branch:'main'})});
  if(!result.ok)throw Error(result.status===409?'成绩发布冲突，请刷新核对后重试。':'发布失败（'+result.status+'），请检查令牌的仓库 Contents 读写权限。');
  official=snapshot;publicState='ready';
  if(scoreContent({...local,records:{...snapshot.records,...local.records}})===scoreContent(snapshot)){local=structuredClone(snapshot);localStorage.setItem(KEY,JSON.stringify(local));localStorage.removeItem(KEY+'-preview');}
  status.textContent='已提交成绩，GitHub Pages 部署完成后所有访客可见。';toast('成绩已发布，网站正在更新。');
 }catch(e){status.textContent=e.message;toast(e.message);}finally{publishing=false;if(button.isConnected)button.disabled=false;}
}
document.addEventListener('click',e=>{if(e.target.closest('#publish-results')){e.preventDefault();publishResults();}if(e.target.closest('#official-preview')){localStorage.removeItem(KEY+'-preview');window.open('index.html#schedule','_blank','noopener');}});

function render(){const {track}=route();$('#main').innerHTML=isWorkbench?`<div class="container content">${workbenchHeader(track)}${calculator(track)}</div>`:home();document.title=isWorkbench?'记分工作台 | 上外杯 #3':'上外杯 #3 · 沉沦者的黑流树海';if(isWorkbench)updateSummary();setActiveNav();}
function setActiveNav(){document.querySelectorAll('.topbar nav a').forEach(a=>{const active=isWorkbench?a.href.includes('workbench.html'):a.hash===(location.hash||'#schedule');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
function download(){const result=S.validate({...local,updatedAt:new Date().toISOString()});const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));a.href=url;a.download='shangwai-cup-3-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出全部本地计分记录。');}
function mergeRecords(data){const d=S.validate(data),overlap=Object.keys(d.records).filter(id=>local.records[id]);if(overlap.length&&!confirm('将覆盖以下选手的本地记录：'+overlap.map(id=>player(id).name).join('、')+'。同时采用导入文件的裁判口径，是否继续？'))return;local.records={...local.records,...d.records};local.policy=d.policy;persist();render();toast('已导入 '+Object.keys(d.records).length+' 位选手的记录。');}
document.addEventListener('click',e=>{
const publicButton=e.target.closest('[data-public-team]');if(publicButton){const opening=publicTeam!==publicButton.dataset.publicTeam;publicTeam=opening?publicButton.dataset.publicTeam:'';const y=scrollY;render();if(opening)document.getElementById('public-team-data')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});else window.scrollTo(0,y);return;}
const a=e.target.closest('[data-player]');if(a)selectedPlayer[player(a.dataset.player).track]=a.dataset.player;
const d=e.target.closest('[data-day]');if(d){selectedDay=d.dataset.day;const y=scrollY;render();window.scrollTo(0,y);}
const t=e.target.closest('[data-rules-track]');if(t){rulesTrack=t.dataset.rulesTrack;const y=scrollY;render();window.scrollTo(0,y);}
const r=e.target.closest('[data-rule]');if(r){e.preventDefault();document.getElementById('rule-'+r.dataset.rule)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}

if(e.target.closest('#export-json')){e.preventDefault();try{download();}catch(err){toast(err.message);}}
if(e.target.closest('#import-button'))$('#import-file').click();

if(e.target.closest('#clear-player')){const p=player(selectedPlayer[route().track]);if(confirm('清空 '+p.name+' 的本地试算记录？已发布成绩不会受影响。')){delete local.records[p.id];persist();render();}}
if(e.target.closest('#copy-official')){if(publicState!=='ready')return toast('已发布数据尚未成功加载。');if(!Object.keys(official.records).length)return toast('目前没有可导入的已发布记录。');try{mergeRecords(official);}catch(err){toast(err.message);}}
});
document.addEventListener('submit',e=>{if(e.target.id==='calculator-form')e.preventDefault();});
document.addEventListener('input',e=>{
const el=e.target;if(!el.closest('#calculator-form')||!el.name)return;
const p=player(selectedPlayer[route().track]);let r=local.records[p.id]||S.fresh(p);
if(el.type==='number'&&!el.validity.valid){el.setAttribute('aria-invalid','true');toast('请输入有效数值；数量需为非负整数。');return;}
el.removeAttribute('aria-invalid');r[el.name]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?(el.name==='base'?'':0):Number(el.value)):el.value;local.records[p.id]=r;
for(const child of document.querySelectorAll('[data-parent]'))child.disabled=!r[child.dataset.parent];
persist();updateSummary();
});
document.addEventListener('change',async e=>{
const el=e.target;
if(el.id==='player-select'){selectedPlayer[route().track]=el.value;render();}


if(el.id==='import-file'&&el.files[0]){const f=el.files[0];try{if(f.size>1000000)throw Error('文件过大，请选择小于 1 MB 的计分 JSON。');mergeRecords(JSON.parse(await f.text()));}catch(err){toast('导入失败：'+err.message);}el.value='';}
});
window.addEventListener('hashchange',()=>{if(isWorkbench){render();window.scrollTo(0,0);}else{setActiveNav();document.getElementById(location.hash.slice(1))?.scrollIntoView();}});render();
async function refreshOfficial(){try{const response=await fetch('results.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('成绩加载失败');const next=S.validate(await response.json()),changed=publicState!=='ready'||scoreContent(next)!==scoreContent(official);official=next;publicState='ready';if(isWorkbench&&!Object.keys(local.records).length&&!localStorage.getItem(KEY+'-preview'))local=structuredClone(official);if(!isWorkbench&&changed){const y=scrollY;render();window.scrollTo(0,y);}}catch(e){publicState='error';}}
window.addEventListener('storage',e=>{if(e.key===KEY||e.key===KEY+'-preview'){try{local=S.validate(JSON.parse(localStorage.getItem(KEY)||'{"schemaVersion":1,"records":{}}'));if(!isWorkbench){const y=scrollY;render();window.scrollTo(0,y);}}catch(err){toast('无法读取计分记录');}}});
refreshOfficial().then(()=>{if(isWorkbench)render();else document.getElementById(location.hash.slice(1))?.scrollIntoView();});
setInterval(()=>{if(!document.hidden&&!isWorkbench)refreshOfficial();},30000);
})();
